FROM tensorflow/tensorflow:2.8.0-gpu-jupyter

RUN pip install --use-feature=2020-resolver transformers torch

# RUN pip install --use-feature=2020-resolver torch==1.10.2+cu113 torchvision==0.11.3+cu113 torchaudio==0.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html